const SCHEMA_VERSION=3;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?.() || ('id-'+Date.now()+'-'+Math.random().toString(16).slice(2));
const clone=x=>typeof structuredClone==='function'?structuredClone(x):JSON.parse(JSON.stringify(x));
const seedStudents=['أحمد محمد علي','خالد حسن إبراهيم','سلمان عبدالله يحيى','زيد هادي أحمد'];
const TYPE_LABELS={homework:'واجب',participation:'مشاركة',quiz:'اختبار قصير',project:'مشروع',practical:'تطبيق عملي',exam:'اختبار',other:'أخرى',legacy:'مرحّل'};
const makeStudent=name=>({id:uid(),name,grades:{},attendance:{},notes:''});
const makeClass=(name='١ / أ',grade='الأول المتوسط',subject='المهارات الرقمية',students=[])=>({id:uid(),name,grade,subject,students,assessmentEvents:[],selectedAssessmentId:null});
const SCHEDULE_DAYS=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس'];
const PERIOD_TIMES={1:['07:00','07:45'],2:['07:45','08:30'],3:['08:45','09:30'],4:['09:45','10:30'],5:['10:30','11:15'],6:['11:15','12:00'],7:['12:00','12:30']};
const makeTeacherSchedule=()=>({
  teacherName:'ابراهيم بن حمود بن علي النعمي',school:'مدرسة ابو السلع الابتدائية والمتوسطة',title:'الجدول الأساسي 1',
  slots:{
    'الأحد-4':{kind:'class',className:'2م د',subject:'الرقمية'},'الأحد-5':{kind:'standby',note:'منتظر 3'},'الأحد-6':{kind:'class',className:'3م ب',subject:'الرقمية'},'الأحد-7':{kind:'class',className:'2م ب',subject:'الرقمية'},
    'الاثنين-3':{kind:'standby',note:'منتظر 4'},'الاثنين-4':{kind:'class',className:'2م أ',subject:'الرقمية'},'الاثنين-5':{kind:'class',className:'2م ج',subject:'الرقمية'},'الاثنين-6':{kind:'class',className:'3م أ',subject:'الرقمية'},'الاثنين-7':{kind:'class',className:'3م ج',subject:'الرقمية'},
    'الثلاثاء-5':{kind:'class',className:'3م ب',subject:'الرقمية'},'الثلاثاء-6':{kind:'class',className:'2م د',subject:'الرقمية'},'الثلاثاء-7':{kind:'class',className:'2م أ',subject:'الرقمية'},
    'الأربعاء-1':{kind:'class',className:'2م ب',subject:'الرقمية'},'الأربعاء-2':{kind:'class',className:'3م أ',subject:'الرقمية'},'الأربعاء-3':{kind:'standby',note:'منتظر 2'},
    'الخميس-1':{kind:'class',className:'3م ج',subject:'الرقمية'},'الخميس-2':{kind:'class',className:'2م ج',subject:'الرقمية'},'الخميس-3':{kind:'standby',note:'منتظر 1'}
  },
  supervision:[{id:uid(),day:'الثلاثاء',date:'10/10',start:'09:30',end:'09:55',title:'إشراف جديد',type:'إشراف',location:'البوابة الرئيسية، المقصف'}]
});
let state={
  schemaVersion:SCHEMA_VERSION,
  appMeta:{school:'',region:'',year:'١٤٤٨ هـ',semester:'الفصل الدراسي الأول',teacher:'',principal:''},
  settings:{gradeAlertThreshold:60,absenceAlertThreshold:3},
  classes:[makeClass('١ / أ','الأول المتوسط','المهارات الرقمية',seedStudents.map(makeStudent)),makeClass('١ / ب','الأول المتوسط','المهارات الرقمية',[])],
  activeClassId:null,
  ui:{activeView:'dashboard',dismissedInstall:false,assessmentMonth:'all',reportPeriod:'all'},
  teacherSchedule:makeTeacherSchedule()
};
state.activeClassId=state.classes[0].id;
let saveTimer=null,openStudentId=null,editingAssessmentId=null,searchTerm='';

function localDateISO(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function monthKey(date){return /^\d{4}-\d{2}/.test(date||'')?String(date).slice(0,7):''}
function currentClass(){return state.classes.find(c=>c.id===state.activeClassId)||state.classes[0]}
function findClass(id){return state.classes.find(c=>c.id===id)}
function findStudent(id){for(const c of state.classes){const s=c.students.find(x=>x.id===id);if(s)return s}}
function findStudentClass(id){return state.classes.find(c=>c.students.some(s=>s.id===id))}
function findAssessment(id,c=currentClass()){return c?.assessmentEvents?.find(a=>a.id===id)}
function ensureStudent(s){s.grades ||= {};s.attendance ||= {};s.notes ||= '';return s}
function ensureAssessment(a){a.id ||= uid();a.title ||= 'تقييم';a.type ||= 'other';a.date ||= '';a.maxScore=Math.max(.5,Number(a.maxScore||a.max||10));a.note ||= '';return a}
function ensureClass(c){c.grade ||= 'الأول المتوسط';c.subject ||= 'المهارات الرقمية';c.students ||= [];c.students.forEach(ensureStudent);c.assessmentEvents ||= [];c.assessmentEvents.forEach(ensureAssessment);if(!c.selectedAssessmentId||!c.assessmentEvents.some(a=>a.id===c.selectedAssessmentId))c.selectedAssessmentId=c.assessmentEvents[0]?.id||null;return c}

function legacyType(field){const n=(field.name||'').toLowerCase();if(/واجب/.test(n))return'homework';if(/مشارك/.test(n))return'participation';if(/اختبار/.test(n))return'quiz';if(/مشروع|بحث/.test(n))return'project';if(/عملي|تطبيق/.test(n))return'practical';return'legacy'}
function migrate(input){
  if(!input||!Array.isArray(input.classes))return null;
  const x=clone(input);
  x.appMeta ||= {school:'',region:'',year:x.meta?.year||'١٤٤٨ هـ',semester:x.meta?.semester||'الفصل الدراسي الأول',teacher:x.meta?.teacher||'',principal:x.meta?.principal||''};
  x.appMeta.school ||= '';x.appMeta.region ||= '';
  x.settings ||= {gradeAlertThreshold:60,absenceAlertThreshold:3};
  x.settings.gradeAlertThreshold=Number(x.settings.gradeAlertThreshold??60);x.settings.absenceAlertThreshold=Number(x.settings.absenceAlertThreshold??3);
  x.teacherSchedule ||= makeTeacherSchedule();x.teacherSchedule.slots ||= {};x.teacherSchedule.supervision ||= [];x.teacherSchedule.teacherName ||= 'ابراهيم بن حمود بن علي النعمي';x.teacherSchedule.school ||= 'مدرسة ابو السلع الابتدائية والمتوسطة';x.teacherSchedule.title ||= 'الجدول الأساسي 1';if(!x.appMeta.teacher)x.appMeta.teacher=x.teacherSchedule.teacherName;if(!x.appMeta.school)x.appMeta.school=x.teacherSchedule.school;
  const oldFields=Array.isArray(x.fields)?x.fields:[];
  x.classes.forEach(c=>{
    c.grade ||= x.meta?.grade||'الأول المتوسط';c.subject ||= x.meta?.subject||'المهارات الرقمية';c.students ||= [];
    c.students.forEach(s=>{s.attendance ||= {};s.notes ||= '';s.grades ||= {}});
    if(!Array.isArray(c.assessmentEvents))c.assessmentEvents=[];
    if(!c.assessmentEvents.length&&oldFields.length){
      for(const f of oldFields){
        for(let slot=0;slot<2;slot++){
          const aid=uid();
          c.assessmentEvents.push({id:aid,title:`${f.name||'تقييم'} ${slot+1}`,type:legacyType(f),date:'',maxScore:Number(f.max||1),note:'مرحّل من الإصدار السابق — التاريخ غير متوفر',legacy:true});
          c.students.forEach(s=>{const v=s.assessments?.[f.id]?.[slot];if(v!==null&&v!==undefined&&v!=='')s.grades[aid]=Number(v)});
        }
      }
    }
    c.assessmentEvents.forEach(ensureAssessment);c.students.forEach(ensureStudent);
    c.selectedAssessmentId=c.assessmentEvents.some(a=>a.id===c.selectedAssessmentId)?c.selectedAssessmentId:c.assessmentEvents[0]?.id||null;
  });
  x.activeClassId=x.classes.some(c=>c.id===x.activeClassId)?x.activeClassId:x.classes[0]?.id;
  x.ui ||= {};x.ui.activeView=x.ui.activeView==='followup'?'assessments':(x.ui.activeView||'dashboard');x.ui.dismissedInstall=!!x.ui.dismissedInstall;x.ui.assessmentMonth ||= 'all';x.ui.reportPeriod ||= 'all';
  x.schemaVersion=SCHEMA_VERSION;delete x.fields;delete x.meta;
  return x;
}

const db={
  memory:{},
  async open(){return new Promise((res,rej)=>{try{const r=indexedDB.open('studentRosterPWA',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('kv'))r.result.createObjectStore('kv')};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)}catch(e){rej(e)}})},
  async get(k){try{const d=await this.open();return await new Promise((res,rej)=>{const t=d.transaction('kv','readonly').objectStore('kv').get(k);t.onsuccess=()=>res(t.result);t.onerror=()=>rej(t.error)})}catch{try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return this.memory[k]??null}}},
  async set(k,v){try{const d=await this.open();await new Promise((res,rej)=>{const t=d.transaction('kv','readwrite').objectStore('kv').put(v,k);t.onsuccess=()=>res();t.onerror=()=>rej(t.error)})}catch{try{localStorage.setItem(k,JSON.stringify(v))}catch{this.memory[k]=clone(v)}}}
};
async function save(){state.schemaVersion=SCHEMA_VERSION;const el=$('#saveStatus');if(el)el.textContent='جارٍ الحفظ…';await db.set('state',state);if(el)el.textContent='محفوظ على هذا الجهاز'}
function queueSave(){clearTimeout(saveTimer);saveTimer=setTimeout(save,220)}
async function load(){const stored=await db.get('state');if(stored){const migrated=migrate(stored);if(migrated)state=migrated}state.classes.forEach(ensureClass);if(!state.activeClassId&&state.classes[0])state.activeClassId=state.classes[0].id;const q=new URLSearchParams(location.search).get('view');if(['dashboard','assessments','attendance','schedule','reports'].includes(q))state.ui.activeView=q;$('#attendanceDate').value=localDateISO();renderAll();showView(state.ui.activeView||'dashboard',false)}

function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2100)}
function arabicNum(n){return Number(n||0).toLocaleString('ar-SA',{maximumFractionDigits:2})}
function pct(n){return n===null||n===undefined?'—':`${Math.round(Number(n)||0).toLocaleString('ar-SA')}٪`}
function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function typeLabel(t){return TYPE_LABELS[t]||'أخرى'}
function statusLabel(s){return ({present:'حاضر',absent:'غائب',late:'متأخر',excused:'مستأذن'})[s]||'غير مسجل'}
function formatDate(d){if(!d)return'بدون تاريخ';try{return new Intl.DateTimeFormat('ar-SA',{year:'numeric',month:'short',day:'numeric'}).format(new Date(d+'T12:00:00'))}catch{return d}}
function monthLabel(m){if(!m)return'بدون تاريخ';try{return new Intl.DateTimeFormat('ar-SA',{year:'numeric',month:'long'}).format(new Date(m+'-15T12:00:00'))}catch{return m}}
function allStudents(){return state.classes.flatMap(c=>c.students)}
function allAssessmentCount(){return state.classes.reduce((n,c)=>n+(c.assessmentEvents?.length||0),0)}
function eventsForPeriod(c,period='all'){return (c.assessmentEvents||[]).filter(a=>period==='all'||monthKey(a.date)===period)}
function scoreSummary(s,c,period='all'){
  const events=eventsForPeriod(c,period);let earned=0,gradedMax=0,totalMax=0,gradedCount=0;
  for(const a of events){totalMax+=Number(a.maxScore)||0;const raw=s.grades?.[a.id];if(raw!==undefined&&raw!==null&&raw!==''&&!Number.isNaN(Number(raw))){earned+=Number(raw);gradedMax+=Number(a.maxScore)||0;gradedCount++}}
  return {earned,gradedMax,totalMax,gradedCount,eventCount:events.length,performance:gradedMax?earned/gradedMax*100:null,completion:events.length?gradedCount/events.length*100:0};
}
function attendanceCounts(s,period='all'){const out={present:0,absent:0,late:0,excused:0,total:0};Object.entries(s.attendance||{}).forEach(([d,v])=>{if(period!=='all'&&monthKey(d)!==period)return;if(out[v]!==undefined){out[v]++;out.total++}});return out}
function classAttendanceForDate(c,date){const out={present:0,absent:0,late:0,excused:0,unmarked:0};c.students.forEach(s=>{const v=s.attendance?.[date];if(out[v]!==undefined)out[v]++;else out.unmarked++});return out}
function riskForStudent(s,c,period='all'){const sc=scoreSummary(s,c,period),at=attendanceCounts(s,period),reasons=[];if(sc.performance!==null&&sc.performance<state.settings.gradeAlertThreshold)reasons.push(`المستوى ${pct(sc.performance)}`);if(at.absent>=state.settings.absenceAlertThreshold)reasons.push(`${arabicNum(at.absent)} غياب`);return {isRisk:reasons.length>0,reasons,score:sc,attendance:at}}
function monthsForClass(c){const set=new Set();(c.assessmentEvents||[]).forEach(a=>{const m=monthKey(a.date);if(m)set.add(m)});c.students.forEach(s=>Object.keys(s.attendance||{}).forEach(d=>{const m=monthKey(d);if(m)set.add(m)}));return [...set].sort().reverse()}

function renderAll(){renderAppMeta();renderClassBars();renderDashboard();renderAssessments();renderAttendance();renderSchedule();renderReports();renderInstallNote()}
function showView(name,saveUi=true){if(!['dashboard','assessments','attendance','schedule','reports'].includes(name))name='dashboard';state.ui.activeView=name;$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));$$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));if(name==='assessments')renderAssessments();if(name==='attendance')renderAttendance();if(name==='schedule')renderSchedule();if(name==='reports')renderReports();window.scrollTo({top:0,behavior:'instant'});if(saveUi)queueSave()}
function setActiveClass(id){if(!findClass(id))return;state.activeClassId=id;searchTerm='';state.ui.assessmentMonth='all';state.ui.reportPeriod='all';const c=currentClass();if(c&&!c.selectedAssessmentId&&c.assessmentEvents[0])c.selectedAssessmentId=c.assessmentEvents[0].id;renderAll();queueSave()}

function renderAppMeta(){$$('[data-app-meta]').forEach(inp=>{const k=inp.dataset.appMeta;if(document.activeElement!==inp)inp.value=state.appMeta[k]||'';inp.oninput=()=>{state.appMeta[k]=inp.value;queueSave()}})}
function classChipMarkup(c){return `<button class="chip ${c.id===state.activeClassId?'active':''}" data-class-switch="${c.id}">${escapeHtml(c.grade)} · ${escapeHtml(c.name)}</button>`}
function renderClassBars(){['#assessmentClassbar','#attendanceClassbar','#reportsClassbar'].forEach(sel=>{const b=$(sel);if(!b)return;b.innerHTML=state.classes.map(classChipMarkup).join('')+`<button class="chip add" data-open-classes>＋ فصل</button>`});$$('[data-class-switch]').forEach(x=>x.onclick=()=>setActiveClass(x.dataset.classSwitch));$$('[data-open-classes]').forEach(x=>x.onclick=openClasses)}

function renderDashboard(){
  const students=allStudents(),today=localDateISO(),absentToday=students.filter(s=>s.attendance?.[today]==='absent').length;
  let riskCount=0;state.classes.forEach(c=>c.students.forEach(s=>{if(riskForStudent(s,c,'all').isRisk)riskCount++}));
  $('#dashboardKpis').innerHTML=`<div class="kpi"><span class="kpi-icon">👥</span><b>${arabicNum(students.length)}</b><span>إجمالي الطلاب</span></div><div class="kpi"><span class="kpi-icon">✓</span><b>${arabicNum(allAssessmentCount())}</b><span>التقييمات المسجلة</span></div><div class="kpi bad"><span class="kpi-icon">○</span><b>${arabicNum(absentToday)}</b><span>غياب اليوم</span></div><div class="kpi warn"><span class="kpi-icon">!</span><b>${arabicNum(riskCount)}</b><span>يحتاجون متابعة</span></div>`;
  $('#classCards').innerHTML=state.classes.length?state.classes.map(c=>{const a=classAttendanceForDate(c,today),risks=c.students.filter(s=>riskForStudent(s,c,'all').isRisk).length;return `<article class="class-card"><div class="class-card-head"><div><h3>${escapeHtml(c.name)}</h3><div class="class-sub">${escapeHtml(c.grade)} · ${escapeHtml(c.subject)}</div></div><span class="count-badge">${arabicNum(c.students.length)} طالب</span></div><div class="class-card-metrics"><div class="mini-metric"><b>${arabicNum(c.assessmentEvents.length)}</b><span>تقييم</span></div><div class="mini-metric"><b>${arabicNum(a.absent)}</b><span>غائب اليوم</span></div><div class="mini-metric ${risks?'risk-text':''}"><b>${arabicNum(risks)}</b><span>متابعة</span></div></div><div class="class-card-actions"><button class="btn primary" data-open-class="${c.id}" data-target="assessments">التقييمات</button><button class="btn" data-open-class="${c.id}" data-target="attendance">الحضور</button><button class="btn" data-open-class="${c.id}" data-target="reports">التقارير</button></div></article>`}).join(''):`<div class="empty-state"><b>لا توجد فصول</b>أضف فصلًا لبدء السجل.</div>`;
  $$('[data-open-class]').forEach(b=>b.onclick=()=>{setActiveClass(b.dataset.openClass);showView(b.dataset.target)})
}

function renderMonthOptions(select,selected,includeAll=true,assessmentOnly=false){const c=currentClass(),months=assessmentOnly?[...new Set(c.assessmentEvents.map(a=>monthKey(a.date)).filter(Boolean))].sort().reverse():monthsForClass(c);select.innerHTML=(includeAll?'<option value="all">الفصل كاملًا</option>':'')+months.map(m=>`<option value="${m}">${escapeHtml(monthLabel(m))}</option>`).join('');if([...select.options].some(o=>o.value===selected))select.value=selected;else select.value='all'}
function sortedEvents(c,filter='all'){return eventsForPeriod(c,filter).slice().sort((a,b)=>{if(!a.date&&!b.date)return 0;if(!a.date)return 1;if(!b.date)return-1;return b.date.localeCompare(a.date)})}
function assessmentCard(a,c){const graded=c.students.filter(s=>s.grades?.[a.id]!==undefined&&s.grades?.[a.id]!==null&&s.grades?.[a.id]!=='').length;return `<button class="assessment-card ${c.selectedAssessmentId===a.id?'active':''}" data-assessment-select="${a.id}"><span class="assessment-type">${escapeHtml(typeLabel(a.type))}</span><b>${escapeHtml(a.title)}</b><small>${escapeHtml(formatDate(a.date))} · من ${arabicNum(a.maxScore)}</small><span class="assessment-progress">${arabicNum(graded)} / ${arabicNum(c.students.length)} مرصود</span></button>`}
function renderAssessments(){
  const c=currentClass();if(!c)return;$('#assessmentHeading').textContent=`التقييمات الزمنية — ${c.name}`;
  renderMonthOptions($('#assessmentMonthFilter'),state.ui.assessmentMonth||'all',true,true);
  const list=sortedEvents(c,state.ui.assessmentMonth||'all');$('#assessmentList').innerHTML=list.length?list.map(a=>assessmentCard(a,c)).join(''):`<div class="empty-state compact-empty"><b>لا توجد تقييمات</b>أضف أول واجب أو اختبار.</div>`;
  $$('[data-assessment-select]').forEach(b=>b.onclick=()=>{c.selectedAssessmentId=b.dataset.assessmentSelect;renderAssessments();queueSave()});
  const a=findAssessment(c.selectedAssessmentId,c);$('#assessmentEmpty').hidden=!!a;$('#assessmentEditor').hidden=!a;if(!a)return;
  $('#selectedAssessmentType').textContent=typeLabel(a.type);$('#selectedAssessmentTitle').textContent=a.title;$('#selectedAssessmentMeta').textContent=`${formatDate(a.date)} · الدرجة العظمى ${arabicNum(a.maxScore)}${a.note?' · '+a.note:''}`;
  renderGradebook(a,c);renderAssessmentSummary(a,c)
}
function renderGradebook(a,c){const term=searchTerm.trim().toLowerCase(),students=term?c.students.filter(s=>s.name.toLowerCase().includes(term)):c.students;$('#gradebookTable').innerHTML=`<thead><tr><th>م</th><th>اسم الطالب</th><th>الدرجة / ${arabicNum(a.maxScore)}</th><th>النسبة</th><th>الحالة</th><th class="no-print">التقرير</th></tr></thead><tbody>${students.length?students.map(s=>{const idx=c.students.findIndex(x=>x.id===s.id),raw=s.grades?.[a.id],has=raw!==undefined&&raw!==null&&raw!=='',val=has?Number(raw):'',pr=has&&a.maxScore?Number(raw)/a.maxScore*100:null;return `<tr><td>${arabicNum(idx+1)}</td><td class="student-name-cell">${escapeHtml(s.name)}</td><td><input class="grade-input" data-grade="${s.id}" type="number" min="0" max="${a.maxScore}" step="0.5" value="${val}" placeholder="—"></td><td>${pct(pr)}</td><td>${has?(pr>=state.settings.gradeAlertThreshold?'<span class="status-tag ok">جيد</span>':'<span class="status-tag risk">متابعة</span>'):'<span class="status-tag neutral">غير مرصود</span>'}</td><td class="no-print"><button class="btn tiny" data-report="${s.id}">عرض</button></td></tr>`}).join(''):`<tr><td colspan="6" class="empty-cell">${term?'لا توجد نتائج مطابقة':'لا يوجد طلاب في هذا الفصل'}</td></tr>`}</tbody>`;
  $$('[data-grade]').forEach(inp=>inp.onchange=()=>{const s=findStudent(inp.dataset.grade);if(!s)return;const v=inp.value.trim();if(v==='')delete s.grades[a.id];else{const n=Number(v);if(Number.isNaN(n)||n<0||n>a.maxScore){toast(`أدخل درجة من 0 إلى ${a.maxScore}`);renderGradebook(a,c);return}s.grades[a.id]=n}renderGradebook(a,c);renderAssessmentSummary(a,c);renderDashboard();renderReports();queueSave()});$$('#gradebookTable [data-report]').forEach(b=>b.onclick=()=>openStudentReport(b.dataset.report))}
function renderAssessmentSummary(a,c){const vals=c.students.map(s=>s.grades?.[a.id]).filter(v=>v!==undefined&&v!==null&&v!==''&&!Number.isNaN(Number(v))).map(Number),graded=vals.length,avg=graded?vals.reduce((x,y)=>x+y,0)/graded:null,pass=vals.filter(v=>a.maxScore&&v/a.maxScore*100>=state.settings.gradeAlertThreshold).length;$('#assessmentSummary').innerHTML=`<div class="stat"><b>${arabicNum(graded)} / ${arabicNum(c.students.length)}</b><span>تم الرصد</span></div><div class="stat"><b>${avg===null?'—':arabicNum(avg)}</b><span>متوسط الدرجة</span></div><div class="stat ok"><b>${avg===null?'—':pct(avg/a.maxScore*100)}</b><span>متوسط النسبة</span></div><div class="stat warn"><b>${arabicNum(graded-pass)}</b><span>تحت حد المتابعة</span></div>`}

function openAssessmentModal(id=null){const a=id?findAssessment(id):null;editingAssessmentId=id;$('#assessmentModalTitle').textContent=a?'تعديل التقييم':'تقييم جديد';$('#assessmentTitleInput').value=a?.title||'';$('#assessmentTypeInput').value=a?.type||'homework';$('#assessmentDateInput').value=a?.date||localDateISO();$('#assessmentMaxInput').value=a?.maxScore||10;$('#assessmentNoteInput').value=a?.note||'';$('#assessmentModal').showModal();setTimeout(()=>$('#assessmentTitleInput').focus(),50)}
function saveAssessment(){const c=currentClass(),title=$('#assessmentTitleInput').value.trim(),date=$('#assessmentDateInput').value,type=$('#assessmentTypeInput').value,maxScore=Number($('#assessmentMaxInput').value),note=$('#assessmentNoteInput').value.trim();if(!title){toast('اكتب اسم التقييم');return}if(!date){toast('اختر تاريخ التقييم');return}if(!maxScore||maxScore<=0){toast('الدرجة العظمى غير صحيحة');return}if(editingAssessmentId){const a=findAssessment(editingAssessmentId,c);if(!a)return;const highest=Math.max(0,...c.students.map(s=>Number(s.grades?.[a.id])).filter(Number.isFinite));if(maxScore<highest){toast(`يوجد طالب درجته ${highest}؛ ارفع الدرجة العظمى أولًا`);return}Object.assign(a,{title,type,date,maxScore,note,legacy:false})}else{const a={id:uid(),title,type,date,maxScore,note,legacy:false};c.assessmentEvents.push(a);c.selectedAssessmentId=a.id}$('#assessmentModal').close();state.ui.assessmentMonth='all';renderAll();queueSave();toast(editingAssessmentId?'تم تعديل التقييم':'تم إنشاء التقييم')}
function deleteAssessment(){const c=currentClass(),a=findAssessment(c.selectedAssessmentId,c);if(!a)return;if(!confirm(`حذف «${a.title}» وجميع درجاته؟`))return;c.assessmentEvents=c.assessmentEvents.filter(x=>x.id!==a.id);c.students.forEach(s=>delete s.grades?.[a.id]);c.selectedAssessmentId=c.assessmentEvents[0]?.id||null;renderAll();queueSave();toast('تم حذف التقييم')}

function addStudent(){const c=currentClass();if(!c)return;const name=prompt('اسم الطالب:');if(!name?.trim())return;c.students.push(makeStudent(name.trim()));renderAll();queueSave();toast('تمت إضافة الطالب')}
function openStudents(){renderStudentsModal();$('#studentsModal').showModal()}
function renderStudentsModal(){const c=currentClass();$('#studentsModalTitle').textContent=`إدارة الطلاب — ${c.name}`;$('#studentsBody').innerHTML=c.students.length?c.students.map((s,i)=>`<div class="student-manage-row" data-student-manage="${s.id}"><span>${arabicNum(i+1)}</span><input value="${escapeHtml(s.name)}" data-student-rename="${s.id}"><button class="iconbtn" data-student-up="${s.id}" title="أعلى">↑</button><button class="iconbtn" data-student-down="${s.id}" title="أسفل">↓</button><button class="iconbtn" data-student-move="${s.id}" title="نقل">↪</button><button class="iconbtn" data-student-delete="${s.id}" title="حذف">×</button></div>`).join(''):`<div class="empty-state"><b>لا يوجد طلاب</b>أضف طالبًا أو استورد CSV.</div>`;$$('[data-student-rename]').forEach(i=>i.onchange=()=>{const s=findStudent(i.dataset.studentRename);if(s)s.name=i.value.trim()||s.name;renderAll();renderStudentsModal();queueSave()});$$('[data-student-up]').forEach(b=>b.onclick=()=>moveStudentRelative(b.dataset.studentUp,-1));$$('[data-student-down]').forEach(b=>b.onclick=()=>moveStudentRelative(b.dataset.studentDown,1));$$('[data-student-delete]').forEach(b=>b.onclick=()=>deleteStudent(b.dataset.studentDelete));$$('[data-student-move]').forEach(b=>b.onclick=()=>moveStudentClass(b.dataset.studentMove))}
function moveStudentRelative(id,delta){const a=currentClass().students,i=a.findIndex(s=>s.id===id),j=i+delta;if(i<0||j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];renderAll();renderStudentsModal();queueSave()}
function deleteStudent(id){const c=findStudentClass(id),s=findStudent(id);if(!c||!s)return;if(!confirm(`حذف الطالب «${s.name}» وجميع درجاته وحضوره؟`))return;c.students=c.students.filter(x=>x.id!==id);renderAll();renderStudentsModal();queueSave()}
function moveStudentClass(id){const from=findStudentClass(id),s=findStudent(id);if(!from||!s)return;if(state.classes.length<2){toast('أضف فصلًا آخر أولًا');return}const targets=state.classes.filter(c=>c.id!==from.id),choices=targets.map((c,i)=>`${i+1}) ${c.grade} · ${c.name}`).join('\n'),n=Number(prompt(`انقل «${s.name}» إلى:\n${choices}`));if(!n||!targets[n-1])return;const target=targets[n-1];from.students=from.students.filter(x=>x.id!==id);target.students.push(s);target.students.sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),'ar',{sensitivity:'base',ignorePunctuation:true,numeric:true}));renderAll();renderStudentsModal();queueSave();toast('تم نقل الطالب وترتيبه أبجديًا')}

function openClasses(){renderClassesModal();$('#classesModal').showModal()}
function renderClassesModal(){const b=$('#classesBody');b.innerHTML=state.classes.map(c=>`<div class="fieldrow class-edit-row" data-class-row="${c.id}"><input data-class-name value="${escapeHtml(c.name)}" aria-label="اسم الفصل"><input data-class-grade value="${escapeHtml(c.grade)}" aria-label="الصف"><input data-class-subject value="${escapeHtml(c.subject)}" aria-label="المادة"><button class="iconbtn" data-class-del="${c.id}" ${state.classes.length===1?'disabled':''}>×</button></div>`).join('');$$('[data-class-row]').forEach(r=>{const c=findClass(r.dataset.classRow);r.querySelector('[data-class-name]').onchange=e=>{c.name=e.target.value.trim()||'فصل';renderAll();queueSave()};r.querySelector('[data-class-grade]').onchange=e=>{c.grade=e.target.value.trim();renderAll();queueSave()};r.querySelector('[data-class-subject]').onchange=e=>{c.subject=e.target.value.trim();renderAll();queueSave()}});$$('[data-class-del]').forEach(x=>x.onclick=()=>{const c=findClass(x.dataset.classDel);if((c.students.length||c.assessmentEvents.length)&&!confirm('الفصل يحتوي سجلات. حذف الفصل سيحذف الطلاب والتقييمات والحضور. متابعة؟'))return;state.classes=state.classes.filter(k=>k.id!==c.id);if(!state.classes.some(k=>k.id===state.activeClassId))state.activeClassId=state.classes[0]?.id;renderClassesModal();renderAll();queueSave()})}
function addClass(){const name=$('#newClassName').value.trim(),grade=$('#newClassGrade').value.trim(),subject=$('#newClassSubject').value.trim();if(!name){toast('اكتب اسم الفصل');return}const c=makeClass(name,grade||'الصف',subject||'المادة',[]);state.classes.push(c);state.activeClassId=c.id;$('#newClassName').value='';$('#newClassGrade').value='';$('#newClassSubject').value='';renderClassesModal();renderAll();queueSave();toast('تمت إضافة الفصل')}


let editingScheduleSlot=null,editingSupervisionId=null;
function scheduleKey(day,period){return `${day}-${period}`}
function scheduleTimeLabel(start,end){const fmt=t=>{if(!t)return'';let [h,m]=t.split(':').map(Number),ap=h>=12?'م':'ص';h=h%12||12;return `${h}:${String(m).padStart(2,'0')} ${ap}`};return start&&end?`${fmt(start)} - ${fmt(end)}`:''}
function scheduleSlot(day,period){const base=state.teacherSchedule.slots?.[scheduleKey(day,period)]||null;if(!base)return null;const pt=PERIOD_TIMES[period]||[];return {...base,start:base.start||pt[0]||'',end:base.end||pt[1]||''}}
function scheduleClassColor(name=''){const palette=['#dbeafe','#dcfce7','#fef3c7','#fce7f3','#ede9fe','#cffafe','#ffedd5','#e2e8f0','#d1fae5'];let h=0;for(const ch of name)h=(h*31+ch.charCodeAt(0))>>>0;return palette[h%palette.length]}
function scheduleCounts(){const slots=Object.values(state.teacherSchedule.slots||{}),teaching=slots.filter(x=>x.kind==='class'),classes=new Set(teaching.map(x=>x.className).filter(Boolean));return {teaching:teaching.length,classes:classes.size}}
function scheduleCellMarkup(day,period,mobile=false){const slot=scheduleSlot(day,period),time=PERIOD_TIMES[period]||['',''];if(!slot)return `<button class="schedule-cell empty" data-schedule-slot="${escapeHtml(day)}|${period}"><span class="period-mobile-label">الحصة ${arabicNum(period)}</span><small>${scheduleTimeLabel(time[0],time[1])}</small><em>＋</em></button>`;if(slot.kind==='standby')return `<button class="schedule-cell standby" data-schedule-slot="${escapeHtml(day)}|${period}"><span class="period-mobile-label">الحصة ${arabicNum(period)}</span><b>${escapeHtml(slot.note||'انتظار')}</b><small>${scheduleTimeLabel(slot.start,slot.end)}</small></button>`;const color=scheduleClassColor(slot.className);return `<button class="schedule-cell class-session" style="--session-color:${color}" data-schedule-slot="${escapeHtml(day)}|${period}"><span class="period-mobile-label">الحصة ${arabicNum(period)}</span><b>${escapeHtml(slot.className||'فصل')}</b><span>${escapeHtml(slot.subject||'')}</span><small>${scheduleTimeLabel(slot.start,slot.end)}</small></button>`}
function renderSchedule(){
  const t=state.teacherSchedule||(state.teacherSchedule=makeTeacherSchedule()),counts=scheduleCounts();
  const teacher=$('#scheduleTeacherInput'),school=$('#scheduleSchoolInput'),title=$('#scheduleTitleInput');if(!teacher)return;
  if(document.activeElement!==teacher)teacher.value=t.teacherName||'';if(document.activeElement!==school)school.value=t.school||'';if(document.activeElement!==title)title.value=t.title||'';
  teacher.oninput=()=>{t.teacherName=teacher.value;state.appMeta.teacher=teacher.value;renderScheduleHeader();queueSave()};school.oninput=()=>{t.school=school.value;state.appMeta.school=school.value;renderScheduleHeader();queueSave()};title.oninput=()=>{t.title=title.value;renderScheduleHeader();queueSave()};
  $('#scheduleStats').innerHTML=`<div><b>${arabicNum(counts.teaching)}</b><span>عدد الحصص</span></div><div><b>${arabicNum(counts.classes)}</b><span>عدد الفصول</span></div>`;
  $('#teacherScheduleTable').innerHTML=`<thead><tr><th>اليوم / الحصة</th>${[1,2,3,4,5,6,7].map(p=>`<th><b>${arabicNum(p)}</b><small>${scheduleTimeLabel(...PERIOD_TIMES[p])}</small></th>`).join('')}</tr></thead><tbody>${SCHEDULE_DAYS.map(day=>`<tr><th>${day}</th>${[1,2,3,4,5,6,7].map(p=>`<td>${scheduleCellMarkup(day,p)}</td>`).join('')}</tr>`).join('')}</tbody>`;
  $('#scheduleMobile').innerHTML=SCHEDULE_DAYS.map(day=>`<article class="schedule-day-card"><h3>${day}</h3><div>${[1,2,3,4,5,6,7].map(p=>scheduleCellMarkup(day,p,true)).join('')}</div></article>`).join('');
  renderScheduleHeader();renderSupervisions();$$('[data-schedule-slot]').forEach(b=>b.onclick=()=>{const [day,p]=b.dataset.scheduleSlot.split('|');openScheduleSlot(day,Number(p))})
}
function renderScheduleHeader(){const t=state.teacherSchedule;if(!$('#schedulePrintHeader'))return;$('#schedulePrintHeader').innerHTML=`<div><b>المملكة العربية السعودية</b><span>وزارة التعليم</span><span>${escapeHtml(t.school||'')}</span></div><div class="schedule-logo-center"><img class="schedule-official-logo" src="./assets/moe-logo.png" alt="شعار وزارة التعليم"><h1>${escapeHtml(t.title||'جدول المعلم')}</h1><b>${escapeHtml(t.teacherName||'')}</b></div><div><b>جدول المعلم</b><span>${escapeHtml(state.appMeta.year||'')}</span><span>${escapeHtml(state.appMeta.semester||'')}</span></div>`}
function openScheduleSlot(day,period){editingScheduleSlot={day,period};const raw=state.teacherSchedule.slots?.[scheduleKey(day,period)]||{},pt=PERIOD_TIMES[period]||['',''];$('#scheduleSlotTitle').textContent=`${day} — الحصة ${arabicNum(period)}`;$('#scheduleSlotKind').value=raw.kind||'empty';$('#scheduleSlotClass').value=raw.className||'';$('#scheduleSlotSubject').value=raw.subject||'';$('#scheduleSlotStart').value=raw.start||pt[0]||'';$('#scheduleSlotEnd').value=raw.end||pt[1]||'';$('#scheduleSlotNote').value=raw.note||'';$('#scheduleSlotModal').showModal()}
function saveScheduleSlot(){if(!editingScheduleSlot)return;const {day,period}=editingScheduleSlot,key=scheduleKey(day,period),kind=$('#scheduleSlotKind').value;if(kind==='empty')delete state.teacherSchedule.slots[key];else state.teacherSchedule.slots[key]={kind,className:$('#scheduleSlotClass').value.trim(),subject:$('#scheduleSlotSubject').value.trim(),start:$('#scheduleSlotStart').value,end:$('#scheduleSlotEnd').value,note:$('#scheduleSlotNote').value.trim()};$('#scheduleSlotModal').close();renderSchedule();queueSave();toast('تم تحديث الجدول')}
function renderSupervisions(){const list=$('#supervisionList');if(!list)return;const items=state.teacherSchedule.supervision||[];list.innerHTML=items.length?items.map(x=>`<article class="supervision-card"><div><b>${escapeHtml(x.day||'')} ${x.date?`<span class="supervision-date">(${escapeHtml(x.date)})</span>`:''}</b><span>${escapeHtml(x.start||'')} - ${escapeHtml(x.end||'')}</span></div><div class="supervision-main"><strong>👁️ ${escapeHtml(x.title||'إشراف')}</strong><span>${escapeHtml(x.type||'إشراف')} — ${escapeHtml(x.location||'')}</span></div><button class="btn tiny no-print" data-edit-supervision="${x.id}">تعديل</button></article>`).join(''):`<div class="empty-state"><b>لا توجد مناوبات مسجلة</b>أضف مناوبة أو إشرافًا جديدًا.</div>`;$$('[data-edit-supervision]').forEach(b=>b.onclick=()=>openSupervision(b.dataset.editSupervision))}
function openSupervision(id=null){editingSupervisionId=id;const x=id?(state.teacherSchedule.supervision||[]).find(v=>v.id===id):null;$('#supervisionModalTitle').textContent=x?'تعديل المناوبة':'إضافة مناوبة';$('#supervisionDay').value=x?.day||'الأحد';$('#supervisionDate').value=x?.date||'';$('#supervisionStart').value=x?.start||'';$('#supervisionEnd').value=x?.end||'';$('#supervisionType').value=x?.type||'إشراف';$('#supervisionTitle').value=x?.title||'';$('#supervisionLocation').value=x?.location||'';$('#deleteSupervisionBtn').hidden=!x;$('#supervisionModal').showModal()}
function saveSupervision(){const obj={day:$('#supervisionDay').value,date:$('#supervisionDate').value.trim(),start:$('#supervisionStart').value,end:$('#supervisionEnd').value,type:$('#supervisionType').value.trim(),title:$('#supervisionTitle').value.trim()||'إشراف',location:$('#supervisionLocation').value.trim()};if(editingSupervisionId){const x=state.teacherSchedule.supervision.find(v=>v.id===editingSupervisionId);if(x)Object.assign(x,obj)}else state.teacherSchedule.supervision.push({id:uid(),...obj});$('#supervisionModal').close();renderSchedule();queueSave();toast('تم حفظ المناوبة')}
function deleteSupervision(){if(!editingSupervisionId)return;if(!confirm('حذف هذه المناوبة؟'))return;state.teacherSchedule.supervision=state.teacherSchedule.supervision.filter(v=>v.id!==editingSupervisionId);$('#supervisionModal').close();renderSchedule();queueSave();toast('تم حذف المناوبة')}
function printTeacherSchedule(){setPrintPage('landscape');document.body.classList.add('print-teacher-schedule');requestAnimationFrame(()=>window.print())}

function renderAttendance(){const c=currentClass();if(!c)return;const date=$('#attendanceDate').value||localDateISO();$('#attendanceHeading').textContent=`تسجيل الحضور — ${c.name}`;const a=classAttendanceForDate(c,date);$('#attendanceStats').innerHTML=`<div class="stat ok"><b>${arabicNum(a.present)}</b><span>حاضر</span></div><div class="stat bad"><b>${arabicNum(a.absent)}</b><span>غائب</span></div><div class="stat late"><b>${arabicNum(a.late)}</b><span>متأخر</span></div><div class="stat excused"><b>${arabicNum(a.excused)}</b><span>مستأذن</span></div>`;$('#attendanceList').innerHTML=c.students.length?c.students.map((s,i)=>{const cur=s.attendance?.[date]||'';return `<div class="attendance-row"><div class="index">${arabicNum(i+1)}</div><div class="student-name">${escapeHtml(s.name)}</div><div class="status-options">${[['present','حاضر'],['absent','غائب'],['late','متأخر'],['excused','مستأذن']].map(([v,l])=>`<button class="status-btn ${cur===v?'active':''}" data-attendance="${s.id}" data-status="${v}">${l}</button>`).join('')}</div></div>`}).join(''):`<div class="empty-state"><b>لا يوجد طلاب</b>أضف طلابًا من شاشة التقييمات أولًا.</div>`;$$('[data-attendance]').forEach(b=>b.onclick=()=>{const s=findStudent(b.dataset.attendance),d=$('#attendanceDate').value||localDateISO();ensureStudent(s);if(s.attendance[d]===b.dataset.status)delete s.attendance[d];else s.attendance[d]=b.dataset.status;renderAttendance();renderDashboard();renderReports();queueSave()})}
function markAllAttendance(status){const c=currentClass(),date=$('#attendanceDate').value||localDateISO();c.students.forEach(s=>{ensureStudent(s);if(!s.attendance[date])s.attendance[date]=status});renderAttendance();renderDashboard();renderReports();queueSave();toast('تم تحديد غير المسجلين حاضر')}
function clearAttendanceDay(){const c=currentClass(),date=$('#attendanceDate').value||localDateISO();if(!confirm('مسح حالات الحضور المسجلة لهذا اليوم؟'))return;c.students.forEach(s=>delete s.attendance?.[date]);renderAttendance();renderDashboard();renderReports();queueSave()}

function officialReportHeader(title,c,periodText,studentName=''){
  const m=state.appMeta||{},school=m.school||'اسم المدرسة',region=m.region||'إدارة التعليم',teacher=m.teacher||'—',principal=m.principal||'—';
  return `<header class="official-report-header" dir="rtl"><div class="official-gov"><b>المملكة العربية السعودية</b><span>وزارة التعليم</span><span>${escapeHtml(region)}</span><span>${escapeHtml(school)}</span></div><div class="official-center"><img class="official-logo" src="./assets/moe-logo.png" alt="شعار وزارة التعليم"><b class="official-ministry-name">وزارة التعليم</b><h1>${escapeHtml(title)}</h1>${studentName?`<div class="official-student">الطالب: <strong>${escapeHtml(studentName)}</strong></div>`:''}</div><div class="official-meta"><div><b>المادة:</b><span>${escapeHtml(c.subject||'—')}</span></div><div><b>العام الدراسي:</b><span>${escapeHtml(m.year||'—')}</span></div><div><b>الفصل الدراسي:</b><span>${escapeHtml(periodText||m.semester||'—')}</span></div><div><b>الصف:</b><span>${escapeHtml(c.grade||'—')}</span></div><div><b>الفصل:</b><span>${escapeHtml(c.name||'—')}</span></div><div><b>معلم المادة:</b><span>${escapeHtml(teacher)}</span></div></div></header>`
}
function officialReportSignatures(){return `<footer class="official-signatures"><div><span>معلم المادة</span><b>${escapeHtml(state.appMeta.teacher||'—')}</b><em>التوقيع: __________________</em></div><div><span>مدير المدرسة</span><b>${escapeHtml(state.appMeta.principal||'—')}</b><em>التوقيع: __________________</em></div></footer>`}
function setPrintPage(orientation='portrait'){let el=document.getElementById('dynamicPrintPage');if(!el){el=document.createElement('style');el.id='dynamicPrintPage';document.head.appendChild(el)}el.textContent=`@page{size:A4 ${orientation};margin:10mm}`}
function clearPrintPage(){document.getElementById('dynamicPrintPage')?.remove()}

function assessmentTypeScore(s,c,period,type){
  const events=eventsForPeriod(c,period).filter(a=>a.type===type);let earned=0,max=0,count=0;
  for(const a of events){const raw=s.grades?.[a.id];if(raw!==undefined&&raw!==null&&raw!==''&&!Number.isNaN(Number(raw))){earned+=Number(raw);max+=Number(a.maxScore)||0;count++}}
  return count?`${arabicNum(earned)} / ${arabicNum(max)}`:'—'
}
function classOfficialSheet(c,period='all'){
  const periodText=period==='all'?state.appMeta.semester:monthLabel(period);
  const rows=c.students.map((s,i)=>{const sc=scoreSummary(s,c,period),at=attendanceCounts(s,period);return `<tr><td class="sheet-num">${arabicNum(i+1)}</td><td class="sheet-name">${escapeHtml(s.name)}</td><td>${assessmentTypeScore(s,c,period,'homework')}</td><td>${assessmentTypeScore(s,c,period,'participation')}</td><td>${assessmentTypeScore(s,c,period,'project')}</td><td>${assessmentTypeScore(s,c,period,'practical')}</td><td>${assessmentTypeScore(s,c,period,'quiz')}</td><td>${assessmentTypeScore(s,c,period,'exam')}</td><td>${sc.gradedMax?`${arabicNum(sc.earned)} / ${arabicNum(sc.gradedMax)}`:'—'}</td><td>${pct(sc.performance)}</td><td>${arabicNum(at.absent)}</td></tr>`}).join('')||'<tr><td colspan="11">لا يوجد طلاب في الفصل</td></tr>';
  return `<div class="official-class-print"><table class="official-class-sheet"><thead><tr class="sheet-header-row"><th colspan="11">${officialReportHeader('كشف متابعة الفصل',c,periodText)}</th></tr><tr class="sheet-columns"><th>م</th><th>اسم الطالب</th><th>الواجبات</th><th>المشاركة والتفاعل</th><th>المشاريع والبحوث</th><th>التطبيقات العملية</th><th>الاختبارات القصيرة</th><th>الاختبارات</th><th>المجموع المرصود</th><th>النسبة</th><th>الغياب</th></tr></thead><tbody>${rows}</tbody></table>${officialReportSignatures()}</div>`
}

function renderReports(){
  const c=currentClass();if(!c)return;renderMonthOptions($('#reportPeriod'),state.ui.reportPeriod||'all');$('#gradeAlertThreshold').value=state.settings.gradeAlertThreshold;$('#absenceAlertThreshold').value=state.settings.absenceAlertThreshold;const period=$('#reportPeriod').value||'all',events=eventsForPeriod(c,period),students=c.students,risks=students.map(s=>({s,...riskForStudent(s,c,period)})),riskList=risks.filter(x=>x.isRisk);const perf=risks.map(x=>x.score.performance).filter(x=>x!==null),avg=perf.length?perf.reduce((a,b)=>a+b,0)/perf.length:null,absence=risks.reduce((n,x)=>n+x.attendance.absent,0);
  $('#reportPrintHeader').innerHTML=classOfficialSheet(c,period);$('#reportKpis').innerHTML=`<div class="stat"><b>${arabicNum(events.length)}</b><span>تقييم في الفترة</span></div><div class="stat ok"><b>${pct(avg)}</b><span>متوسط الأداء المرصود</span></div><div class="stat bad"><b>${arabicNum(absence)}</b><span>إجمالي الغياب</span></div><div class="stat warn"><b>${arabicNum(riskList.length)}</b><span>يحتاجون متابعة</span></div>`;
  $('#riskBanner').innerHTML=riskList.length?`<div class="risk-box"><b>تنبيه متابعة: ${arabicNum(riskList.length)} طالب</b><span>الطالب يظهر هنا إذا انخفض أداؤه المرصود عن ${arabicNum(state.settings.gradeAlertThreshold)}٪ أو بلغ غيابه ${arabicNum(state.settings.absenceAlertThreshold)} أيام في الفترة المحددة.</span></div>`:`<div class="risk-box clear"><b>لا توجد تنبيهات وفق الحدود الحالية</b><span>يمكنك تعديل حدود التنبيه من أعلى التقرير.</span></div>`;
  $('#studentReportList').innerHTML=students.length?risks.map((x,i)=>{const r=x,sc=r.score,at=r.attendance;return `<div class="student-report-row ${r.isRisk?'risk-row':''}"><div>${arabicNum(i+1)}</div><div><b>${escapeHtml(r.s.name)} ${r.isRisk?'<span class="risk-dot" title="يحتاج متابعة">!</span>':''}</b><div class="subtle">${r.isRisk?escapeHtml(r.reasons.join(' · ')):`${arabicNum(sc.gradedCount)} من ${arabicNum(sc.eventCount)} تقييمات مرصودة`}</div></div><div class="metric"><b>${pct(sc.performance)}</b><span>الأداء</span></div><div class="metric"><b>${pct(sc.completion)}</b><span>اكتمال الرصد</span></div><div class="metric hide-tablet"><b>${arabicNum(at.absent)}</b><span>غياب</span></div><button class="btn" data-report="${r.s.id}">عرض التقرير</button></div>`}).join(''):`<div class="empty-state"><b>لا توجد تقارير بعد</b>أضف طلابًا إلى الفصل.</div>`;$$('#studentReportList [data-report]').forEach(b=>b.onclick=()=>openStudentReport(b.dataset.report))
}
function trendChart(s,c,period){const pts=eventsForPeriod(c,period).filter(a=>a.date&&s.grades?.[a.id]!==undefined&&s.grades?.[a.id]!==null&&a.maxScore>0).sort((a,b)=>a.date.localeCompare(b.date)).map(a=>({a,p:Number(s.grades[a.id])/a.maxScore*100}));if(pts.length<2)return `<div class="trend-empty">يحتاج الرسم إلى تقييمين مؤرخين على الأقل.</div>`;const w=560,h=160,pad=26,dx=(w-pad*2)/(pts.length-1),coords=pts.map((x,i)=>({x:pad+i*dx,y:h-pad-(Math.max(0,Math.min(100,x.p))/100)*(h-pad*2),...x})),poly=coords.map(p=>`${p.x.toFixed(1)},${p.y.toFixed(1)}`).join(' ');return `<div class="trend-wrap"><svg class="trend-chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="تطور مستوى الطالب"><line x1="${pad}" y1="${pad}" x2="${pad}" y2="${h-pad}"/><line x1="${pad}" y1="${h-pad}" x2="${w-pad}" y2="${h-pad}"/><line class="mid" x1="${pad}" y1="${h/2}" x2="${w-pad}" y2="${h/2}"/><polyline points="${poly}" fill="none"/><g>${coords.map(p=>`<circle cx="${p.x}" cy="${p.y}" r="4"><title>${escapeHtml(p.a.title)}: ${Math.round(p.p)}%</title></circle>`).join('')}</g><text x="4" y="${pad+4}">١٠٠٪</text><text x="8" y="${h-pad+4}">٠٪</text></svg><div class="trend-labels"><span>${escapeHtml(formatDate(pts[0].a.date))}</span><span>${escapeHtml(formatDate(pts.at(-1).a.date))}</span></div></div>`}
function studentAssessmentRows(s,c,period){const events=eventsForPeriod(c,period).slice().sort((a,b)=>(a.date||'').localeCompare(b.date||''));return events.map(a=>{const v=s.grades?.[a.id],has=v!==undefined&&v!==null&&v!=='',pr=has&&a.maxScore?Number(v)/a.maxScore*100:null;return `<tr><td>${escapeHtml(formatDate(a.date))}</td><td>${escapeHtml(typeLabel(a.type))}</td><td>${escapeHtml(a.title)}</td><td>${has?`${arabicNum(v)} / ${arabicNum(a.maxScore)}`:'—'}</td><td>${pct(pr)}</td></tr>`}).join('')||'<tr><td colspan="5">لا توجد تقييمات في هذه الفترة</td></tr>'}
function recentAttendanceRows(s,period){return Object.entries(s.attendance||{}).filter(([d])=>period==='all'||monthKey(d)===period).sort((a,b)=>b[0].localeCompare(a[0])).slice(0,20).map(([d,v])=>`<tr><td>${escapeHtml(formatDate(d))}</td><td>${escapeHtml(statusLabel(v))}</td></tr>`).join('')||'<tr><td colspan="2">لا توجد بيانات حضور في هذه الفترة</td></tr>'}
function openStudentReport(id){const s=findStudent(id),c=findStudentClass(id);if(!s||!c)return;openStudentId=id;const period=state.ui.reportPeriod||'all',r=riskForStudent(s,c,period),sc=r.score,a=r.attendance,periodText=period==='all'?state.appMeta.semester:monthLabel(period);$('#studentModalTitle').textContent=`تقرير ${s.name}`;$('#studentReportPrint').innerHTML=`${officialReportHeader('تقرير متابعة الطالب',c,periodText,s.name)}${r.isRisk?`<div class="risk-box report-risk"><b>يحتاج متابعة</b><span>${escapeHtml(r.reasons.join(' · '))}</span></div>`:''}<div class="student-report-grid"><div class="report-box"><b>${pct(sc.performance)}</b><span>الأداء المرصود</span></div><div class="report-box"><b>${pct(sc.completion)}</b><span>اكتمال الرصد</span></div><div class="report-box"><b>${arabicNum(a.absent)}</b><span>غياب</span></div><div class="report-box"><b>${arabicNum(a.late)}</b><span>تأخر</span></div></div><section class="report-section"><h3>تطور المستوى</h3>${trendChart(s,c,period)}</section><section class="report-section"><h3>سجل التقييمات</h3><table class="detail-table"><thead><tr><th>التاريخ</th><th>النوع</th><th>التقييم</th><th>الدرجة</th><th>النسبة</th></tr></thead><tbody>${studentAssessmentRows(s,c,period)}</tbody></table></section><section class="report-section"><h3>سجل الحضور</h3><div class="student-report-grid compact-grid"><div class="report-box"><b>${arabicNum(a.present)}</b><span>حاضر</span></div><div class="report-box"><b>${arabicNum(a.absent)}</b><span>غائب</span></div><div class="report-box"><b>${arabicNum(a.late)}</b><span>متأخر</span></div><div class="report-box"><b>${arabicNum(a.excused)}</b><span>مستأذن</span></div></div><table class="detail-table attendance-history"><thead><tr><th>التاريخ</th><th>الحالة</th></tr></thead><tbody>${recentAttendanceRows(s,period)}</tbody></table></section>${s.notes?`<div class="student-report-header note-box"><b>ملاحظات المعلم</b><p>${escapeHtml(s.notes)}</p></div>`:''}${officialReportSignatures()}`;$('#studentNotes').value=s.notes||'';if(!$('#studentModal').open)$('#studentModal').showModal()}
function saveStudentNotes(){const s=findStudent(openStudentId);if(!s)return;s.notes=$('#studentNotes').value.trim();queueSave();openStudentReport(openStudentId);toast('تم حفظ الملاحظات')}
function printStudent(){setPrintPage('portrait');document.body.classList.add('print-student');requestAnimationFrame(()=>window.print())}
function printClassReport(){setPrintPage('landscape');document.body.classList.add('print-class-summary');showView('reports',false);requestAnimationFrame(()=>window.print())}

function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const ch=text[i],n=text[i+1];if(ch==='"'&&q&&n==='"'){cell+='"';i++}else if(ch==='"'){q=!q}else if(ch===','&&!q){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!q){if(ch==='\r'&&n==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell=''}else cell+=ch}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows}
function csvHeaderIndex(headers,names){return headers.findIndex(h=>names.some(n=>h.toLowerCase()===n.toLowerCase()))}
function normalizeImportText(v=''){return String(v??'').trim().replace(/\s+/g,' ')}
function latinDigits(v=''){return normalizeImportText(v).replace(/[٠-٩]/g,d=>'0123456789'['٠١٢٣٤٥٦٧٨٩'.indexOf(d)]).replace(/[۰-۹]/g,d=>'0123456789'['۰۱۲۳۴۵۶۷۸۹'.indexOf(d)])}
function arabicDigits(v=''){return String(v??'').replace(/\d/g,d=>'٠١٢٣٤٥٦٧٨٩'[Number(d)])}
function studentNameKey(v=''){return normalizeImportText(v).normalize('NFKC').replace(/[\u064B-\u065F\u0670\u0640]/g,'').replace(/[أإآ]/g,'ا').replace(/ى/g,'ي').toLowerCase()}
function gradeImportKey(v=''){return latinDigits(v).normalize('NFKC').toLowerCase()}
function sectionImportKey(v=''){return latinDigits(v).replace(/^الفصل\s*/,'').replace(/\s+/g,'').toLowerCase()}
function findImportedClass(grade,section){const g=gradeImportKey(grade),s=sectionImportKey(section);return state.classes.find(c=>gradeImportKey(c.grade)===g&&sectionImportKey(c.name)===s)}
function starterStateOnly(){const starter=new Set(seedStudents.map(studentNameKey));return state.classes.length<=2&&state.classes.every(c=>(c.assessmentEvents||[]).length===0&&(c.students||[]).every(s=>{const hasRecords=Object.keys(s.grades||{}).length||Object.keys(s.attendance||{}).length||String(s.notes||'').trim();return !hasRecords&&starter.has(studentNameKey(s.name))}))}
function gradeSortValue(v=''){const k=gradeImportKey(v);if(/الأول|اول/.test(k))return 1;if(/الثاني|ثاني/.test(k))return 2;if(/الثالث|ثالث/.test(k))return 3;return 99}
function sortImportedClasses(){state.classes.sort((a,b)=>gradeSortValue(a.grade)-gradeSortValue(b.grade)||Number(sectionImportKey(a.name)||999)-Number(sectionImportKey(b.name)||999)||String(a.name).localeCompare(String(b.name),'ar'))}
async function importSchoolCSV(rows,headers){
  const nameIdx=csvHeaderIndex(headers,['الاسم','اسم الطالب','name']),gradeIdx=csvHeaderIndex(headers,['الصف','grade']),sectionIdx=csvHeaderIndex(headers,['الفصل','الشعبة','section','class']);
  if(nameIdx<0||gradeIdx<0||sectionIdx<0)return false;
  const schoolIdx=csvHeaderIndex(headers,['المدرسة','school']),regionIdx=csvHeaderIndex(headers,['الإدارة','الادارة','المنطقة','region']);
  const grouped=new Map(),schools=new Set(),regions=new Set();
  for(const r of rows.slice(1)){const name=normalizeImportText(r[nameIdx]),grade=normalizeImportText(r[gradeIdx]),section=normalizeImportText(r[sectionIdx]);if(!name||!grade||!section)continue;const key=`${gradeImportKey(grade)}||${sectionImportKey(section)}`;if(!grouped.has(key))grouped.set(key,{grade,section,names:[],seen:new Set()});const g=grouped.get(key),nk=studentNameKey(name);if(!g.seen.has(nk)){g.seen.add(nk);g.names.push(name)}if(schoolIdx>=0&&normalizeImportText(r[schoolIdx]))schools.add(normalizeImportText(r[schoolIdx]));if(regionIdx>=0&&normalizeImportText(r[regionIdx]))regions.add(normalizeImportText(r[regionIdx]))}
  const groups=[...grouped.values()].sort((a,b)=>gradeSortValue(a.grade)-gradeSortValue(b.grade)||Number(sectionImportKey(a.section)||999)-Number(sectionImportKey(b.section)||999)),total=groups.reduce((n,g)=>n+g.names.length,0);if(!total)return false;
  const preview=groups.map(g=>`${g.grade} — الفصل ${arabicDigits(latinDigits(g.section))}: ${g.names.length} طالب`).join('\n');
  const sync=confirm(`تم العثور على ${total} طالبًا موزعين على ${groups.length} فصول:\n\n${preview}\n\nموافق = مزامنة قوائم هذه الفصول مع الملف مع الاحتفاظ بدرجات وحضور الطالب المطابق بالاسم.\nإلغاء = إضافة الطلاب الجدد فقط دون حذف أي طالب موجود.`);
  const defaultSubject=currentClass()?.subject||'المهارات الرقمية',cleanStarter=starterStateOnly();if(cleanStarter)state.classes=[];const touched=[];
  for(const g of groups){const sectionLabel=arabicDigits(latinDigits(g.section));let c=findImportedClass(g.grade,g.section);if(!c){c=makeClass(sectionLabel,g.grade,defaultSubject,[]);state.classes.push(c)}else{c.grade=g.grade;c.name=sectionLabel}const existing=new Map(c.students.map(s=>[studentNameKey(s.name),s]));if(sync)c.students=g.names.map(name=>existing.get(studentNameKey(name))||makeStudent(name));else for(const name of g.names){const k=studentNameKey(name);if(!existing.has(k)){const st=makeStudent(name);c.students.push(st);existing.set(k,st)}}touched.push(c)}
  if(schools.size===1)state.appMeta.school=[...schools][0];if(regions.size===1)state.appMeta.region=[...regions][0];sortImportedClasses();if(touched[0])state.activeClassId=touched[0].id;renderAll();if($('#studentsModal').open)renderStudentsModal();queueSave();toast(`تم توزيع ${total} طالبًا على ${groups.length} فصول`);return true
}
async function importCSV(file){const text=await file.text(),rows=parseCSV(text);if(rows.length<2){toast('ملف CSV فارغ أو غير صالح');return}const headers=rows[0].map(x=>x.trim().replace(/^\uFEFF/,''));if(await importSchoolCSV(rows,headers))return;let idx=headers.findIndex(h=>/^(الاسم|اسم الطالب|name)$/i.test(h));if(idx<0)idx=headers.length-1;const names=rows.slice(1).map(r=>(r[idx]||'').trim()).filter(Boolean);if(!names.length){toast('لم أجد أسماء طلاب');return}const replace=confirm(`تم العثور على ${names.length} طالبًا.\nموافق = استبدال طلاب الفصل الحالي\nإلغاء = إضافة إلى الموجود`);if(replace)currentClass().students=[];const existing=new Set(currentClass().students.map(s=>studentNameKey(s.name)));for(const name of names){const k=studentNameKey(name);if(!existing.has(k)){currentClass().students.push(makeStudent(name));existing.add(k)}}renderAll();if($('#studentsModal').open)renderStudentsModal();queueSave();toast(`تم استيراد ${names.length} طالبًا`)}
function csvCell(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function exportCurrentClassCSV(){const c=currentClass(),events=c.assessmentEvents.slice().sort((a,b)=>(a.date||'').localeCompare(b.date||'')),headers=['م','الاسم',...events.map(a=>`${a.title} | ${a.date||'بدون تاريخ'} | من ${a.maxScore}`),'نسبة الأداء','اكتمال الرصد','الغياب','التأخر','ملاحظات'];const lines=[headers.map(csvCell).join(',')];c.students.forEach((s,i)=>{const a=attendanceCounts(s),sc=scoreSummary(s,c),vals=events.map(e=>s.grades?.[e.id]??'');lines.push([i+1,s.name,...vals,sc.performance===null?'':Math.round(sc.performance*100)/100,Math.round(sc.completion*100)/100,a.absent,a.late,s.notes||''].map(csvCell).join(','))});download(`سجل-${c.name}-${localDateISO()}.csv`,'\uFEFF'+lines.join('\n'),'text/csv;charset=utf-8')}
function download(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();const url=a.href;a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function backup(){const copy=clone(state);copy.exportedAt=new Date().toISOString();download(`student-roster-backup-${localDateISO()}.json`,JSON.stringify(copy,null,2))}
async function restore(file){try{const x=JSON.parse(await file.text()),m=migrate(x);if(!m)throw 0;if(!confirm('سيتم استبدال السجلات الحالية بالنسخة الاحتياطية. متابعة؟'))return;state=m;await save();renderAll();showView('dashboard',false);toast('تمت الاستعادة')}catch{toast('ملف النسخة الاحتياطية غير صالح')}}
function renderInstallNote(){const isIOS=/iphone|ipad|ipod/i.test(navigator.userAgent),standalone=window.matchMedia('(display-mode: standalone)').matches||navigator.standalone;$('#installNote').style.display=isIOS&&!standalone&&!state.ui.dismissedInstall?'block':'none'}

document.addEventListener('click',e=>{const nav=e.target.closest('[data-nav]');if(nav)showView(nav.dataset.nav);if(e.target.matches('[data-close]'))e.target.closest('dialog').close();if(e.target.matches('[data-mark-all]'))markAllAttendance(e.target.dataset.markAll);if(e.target.matches('[data-clear-attendance]'))clearAttendanceDay()});
$('#dashAddAssessment').onclick=()=>{showView('assessments');openAssessmentModal()};$('#dashAddStudent').onclick=()=>{showView('assessments');addStudent()};$('#addAssessmentBtn').onclick=()=>openAssessmentModal();$('#editAssessmentBtn').onclick=()=>openAssessmentModal(currentClass().selectedAssessmentId);$('#deleteAssessmentBtn').onclick=deleteAssessment;$('#saveAssessmentBtn').onclick=saveAssessment;
$('#assessmentMonthFilter').onchange=e=>{state.ui.assessmentMonth=e.target.value;renderAssessments();queueSave()};$('#studentSearch').oninput=e=>{searchTerm=e.target.value;renderAssessments()};$('#addStudentBtn').onclick=addStudent;$('#assessmentAddStudentBtn').onclick=addStudent;$('#manageStudentsBtn').onclick=openStudents;$('#manageStudentsBtnTop').onclick=openStudents;$('#studentsAddBtn').onclick=()=>{addStudent();renderStudentsModal()};$('#studentsImportBtn').onclick=()=>$('#csvInput').click();$('#importBtn').onclick=()=>$('#csvInput').click();$('#csvInput').onchange=e=>{if(e.target.files[0])importCSV(e.target.files[0]);e.target.value=''};$('#exportCsvBtn').onclick=exportCurrentClassCSV;
$('#manageClassesBtn').onclick=openClasses;$('#addClassBtn').onclick=addClass;$('#backupBtn').onclick=backup;$('#restoreBtn').onclick=()=>$('#restoreInput').click();$('#restoreInput').onchange=e=>{if(e.target.files[0])restore(e.target.files[0]);e.target.value=''};$('#attendanceDate').onchange=renderAttendance;
$('#addSupervisionBtn').onclick=()=>openSupervision();$('#printScheduleBtn').onclick=printTeacherSchedule;$('#saveScheduleSlotBtn').onclick=saveScheduleSlot;$('#saveSupervisionBtn').onclick=saveSupervision;$('#deleteSupervisionBtn').onclick=deleteSupervision;
$('#reportPeriod').onchange=e=>{state.ui.reportPeriod=e.target.value;renderReports();queueSave()};$('#gradeAlertThreshold').onchange=e=>{state.settings.gradeAlertThreshold=Math.max(0,Math.min(100,Number(e.target.value)||60));renderAll();queueSave()};$('#absenceAlertThreshold').onchange=e=>{state.settings.absenceAlertThreshold=Math.max(1,Number(e.target.value)||3);renderAll();queueSave()};$('#printClassReportBtn').onclick=printClassReport;$('#saveStudentNotesBtn').onclick=saveStudentNotes;$('#printStudentBtn').onclick=printStudent;$('#dismissInstall').onclick=()=>{state.ui.dismissedInstall=true;renderInstallNote();queueSave()};
window.addEventListener('afterprint',()=>{document.body.classList.remove('print-student','print-class-summary','print-teacher-schedule');clearPrintPage()});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
load();
